# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1142, 875)
        MainWindow.setMinimumSize(QtCore.QSize(1142, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(550, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(550, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 537, 882))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ProcTabs = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProcTabs.sizePolicy().hasHeightForWidth())
        self.ProcTabs.setSizePolicy(sizePolicy)
        self.ProcTabs.setMinimumSize(QtCore.QSize(525, 0))
        self.ProcTabs.setMaximumSize(QtCore.QSize(525, 16777215))
        self.ProcTabs.setMouseTracking(True)
        self.ProcTabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ProcTabs.setElideMode(QtCore.Qt.ElideLeft)
        self.ProcTabs.setUsesScrollButtons(True)
        self.ProcTabs.setTabsClosable(False)
        self.ProcTabs.setTabBarAutoHide(True)
        self.ProcTabs.setObjectName("ProcTabs")
        self.LoadTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoadTab.sizePolicy().hasHeightForWidth())
        self.LoadTab.setSizePolicy(sizePolicy)
        self.LoadTab.setMinimumSize(QtCore.QSize(940, 0))
        self.LoadTab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LoadTab.setObjectName("LoadTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.LoadTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.inputRAWParametersBox = QtWidgets.QGroupBox(self.LoadTab)
        self.inputRAWParametersBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputRAWParametersBox.sizePolicy().hasHeightForWidth())
        self.inputRAWParametersBox.setSizePolicy(sizePolicy)
        self.inputRAWParametersBox.setMinimumSize(QtCore.QSize(505, 125))
        self.inputRAWParametersBox.setMaximumSize(QtCore.QSize(505, 16777215))
        self.inputRAWParametersBox.setObjectName("inputRAWParametersBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.inputRAWParametersBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.inputRAWParametersBox)
        self.label.setToolTip("")
        self.label.setStatusTip("")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.stacksLineEdit = QtWidgets.QLineEdit(self.inputRAWParametersBox)
        self.stacksLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stacksLineEdit.setToolTip("<html><head/><body><p>Set the stacks that you would like processed.</p><p>This must be a valid set of numpy array indices. Remember that Python uses non end-inclusive indexing. </p><p>So things like [1:24] will include stacks 1-23</p><p>Furthermore [1:8,12:24] will include stacks 1-7 and 12:23. Any list of valid indices will be accepted, but they must be comma seperated. </p></body></html>")
        self.stacksLineEdit.setObjectName("stacksLineEdit")
        self.gridLayout_4.addWidget(self.stacksLineEdit, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.inputRAWParametersBox)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 0, 2, 1, 1)
        self.DeadTimeSpinBox = QtWidgets.QDoubleSpinBox(self.inputRAWParametersBox)
        self.DeadTimeSpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.DeadTimeSpinBox.setMinimum(0.5)
        self.DeadTimeSpinBox.setSingleStep(0.5)
        self.DeadTimeSpinBox.setProperty("value", 5.0)
        self.DeadTimeSpinBox.setObjectName("DeadTimeSpinBox")
        self.gridLayout_4.addWidget(self.DeadTimeSpinBox, 0, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.inputRAWParametersBox)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 1, 0, 1, 1)
        self.dataChanLineEdit = QtWidgets.QLineEdit(self.inputRAWParametersBox)
        self.dataChanLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dataChanLineEdit.setObjectName("dataChanLineEdit")
        self.gridLayout_4.addWidget(self.dataChanLineEdit, 1, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.inputRAWParametersBox)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 1, 2, 1, 1)
        self.refChanLineEdit = QtWidgets.QLineEdit(self.inputRAWParametersBox)
        self.refChanLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.refChanLineEdit.setText("")
        self.refChanLineEdit.setObjectName("refChanLineEdit")
        self.gridLayout_4.addWidget(self.refChanLineEdit, 1, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.inputRAWParametersBox)
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 2, 0, 1, 1)
        self.FIDProcComboBox = QtWidgets.QComboBox(self.inputRAWParametersBox)
        self.FIDProcComboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.FIDProcComboBox.setObjectName("FIDProcComboBox")
        self.gridLayout_4.addWidget(self.FIDProcComboBox, 2, 1, 1, 1)
        self.plotImportCheckBox = QtWidgets.QCheckBox(self.inputRAWParametersBox)
        self.plotImportCheckBox.setEnabled(False)
        self.plotImportCheckBox.setChecked(True)
        self.plotImportCheckBox.setObjectName("plotImportCheckBox")
        self.gridLayout_4.addWidget(self.plotImportCheckBox, 2, 2, 1, 1)
        self.loadDataPushButton = QtWidgets.QPushButton(self.inputRAWParametersBox)
        self.loadDataPushButton.setEnabled(False)
        self.loadDataPushButton.setStyleSheet("#loadDataPushButton {\n"
"    background: green;\n"
"}\n"
"\n"
"#loadDataPushButton:disabled {\n"
"    background: black;\n"
"}")
        self.loadDataPushButton.setObjectName("loadDataPushButton")
        self.gridLayout_4.addWidget(self.loadDataPushButton, 2, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.inputRAWParametersBox)
        self.downSampleGroupBox = QtWidgets.QGroupBox(self.LoadTab)
        self.downSampleGroupBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downSampleGroupBox.sizePolicy().hasHeightForWidth())
        self.downSampleGroupBox.setSizePolicy(sizePolicy)
        self.downSampleGroupBox.setMinimumSize(QtCore.QSize(505, 90))
        self.downSampleGroupBox.setMaximumSize(QtCore.QSize(505, 16777215))
        self.downSampleGroupBox.setCheckable(True)
        self.downSampleGroupBox.setObjectName("downSampleGroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.downSampleGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.truncateSpinBox = QtWidgets.QSpinBox(self.downSampleGroupBox)
        self.truncateSpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.truncateSpinBox.setMaximum(1000)
        self.truncateSpinBox.setProperty("value", 0)
        self.truncateSpinBox.setObjectName("truncateSpinBox")
        self.gridLayout_5.addWidget(self.truncateSpinBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.downSampleGroupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.downSampleSpinBox = QtWidgets.QSpinBox(self.downSampleGroupBox)
        self.downSampleSpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.downSampleSpinBox.setMinimum(1)
        self.downSampleSpinBox.setMaximum(5)
        self.downSampleSpinBox.setProperty("value", 5)
        self.downSampleSpinBox.setObjectName("downSampleSpinBox")
        self.gridLayout_5.addWidget(self.downSampleSpinBox, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.downSampleGroupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 1, 0, 1, 1)
        self.downSampleGO = QtWidgets.QPushButton(self.downSampleGroupBox)
        self.downSampleGO.setStyleSheet("#downSampleGO {\n"
"    background: green;\n"
"}\n"
"\n"
"#downSampleGO:disabled{\n"
"    background: black;\n"
"}")
        self.downSampleGO.setObjectName("downSampleGO")
        self.gridLayout_5.addWidget(self.downSampleGO, 1, 2, 1, 1)
        self.dsPlot = QtWidgets.QCheckBox(self.downSampleGroupBox)
        self.dsPlot.setChecked(True)
        self.dsPlot.setObjectName("dsPlot")
        self.gridLayout_5.addWidget(self.dsPlot, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.downSampleGroupBox)
        self.windowFilterGroupBox = QtWidgets.QGroupBox(self.LoadTab)
        self.windowFilterGroupBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windowFilterGroupBox.sizePolicy().hasHeightForWidth())
        self.windowFilterGroupBox.setSizePolicy(sizePolicy)
        self.windowFilterGroupBox.setMinimumSize(QtCore.QSize(505, 90))
        self.windowFilterGroupBox.setMaximumSize(QtCore.QSize(505, 16777215))
        self.windowFilterGroupBox.setCheckable(True)
        self.windowFilterGroupBox.setObjectName("windowFilterGroupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.windowFilterGroupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_55 = QtWidgets.QLabel(self.windowFilterGroupBox)
        self.label_55.setObjectName("label_55")
        self.gridLayout_6.addWidget(self.label_55, 4, 0, 1, 1)
        self.fdDesignPushButton = QtWidgets.QPushButton(self.windowFilterGroupBox)
        self.fdDesignPushButton.setStyleSheet("")
        self.fdDesignPushButton.setObjectName("fdDesignPushButton")
        self.gridLayout_6.addWidget(self.fdDesignPushButton, 1, 3, 1, 1)
        self.windowFilterGO = QtWidgets.QPushButton(self.windowFilterGroupBox)
        self.windowFilterGO.setStyleSheet("#windowFilterGO {\n"
"    background: green;\n"
"}\n"
"\n"
"#windowFilterGO:disabled{\n"
"    background: black;\n"
"}")
        self.windowFilterGO.setObjectName("windowFilterGO")
        self.gridLayout_6.addWidget(self.windowFilterGO, 4, 3, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.windowFilterGroupBox)
        self.label_48.setObjectName("label_48")
        self.gridLayout_6.addWidget(self.label_48, 1, 0, 1, 1)
        self.windowBandwidthSpinBox = QtWidgets.QDoubleSpinBox(self.windowFilterGroupBox)
        self.windowBandwidthSpinBox.setDecimals(1)
        self.windowBandwidthSpinBox.setMaximum(1200.0)
        self.windowBandwidthSpinBox.setProperty("value", 600.0)
        self.windowBandwidthSpinBox.setObjectName("windowBandwidthSpinBox")
        self.gridLayout_6.addWidget(self.windowBandwidthSpinBox, 1, 1, 2, 1)
        self.lcdWinDead = QtWidgets.QLCDNumber(self.windowFilterGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdWinDead.sizePolicy().hasHeightForWidth())
        self.lcdWinDead.setSizePolicy(sizePolicy)
        self.lcdWinDead.setStyleSheet("#lcdWinDead {\n"
"color: green;\n"
"background: black;\n"
"}\n"
"\n"
"#lcdWinDead:disabled {\n"
"color: grey;\n"
"background: dark grey;\n"
"}")
        self.lcdWinDead.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdWinDead.setObjectName("lcdWinDead")
        self.gridLayout_6.addWidget(self.lcdWinDead, 4, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.windowFilterGroupBox)
        self.label_45.setObjectName("label_45")
        self.gridLayout_6.addWidget(self.label_45, 0, 0, 1, 1)
        self.windowTypeComboBox = QtWidgets.QComboBox(self.windowFilterGroupBox)
        self.windowTypeComboBox.setObjectName("windowTypeComboBox")
        self.windowTypeComboBox.addItem("")
        self.windowTypeComboBox.addItem("")
        self.windowTypeComboBox.addItem("")
        self.windowTypeComboBox.addItem("")
        self.gridLayout_6.addWidget(self.windowTypeComboBox, 0, 1, 1, 1)
        self.windowTrim = QtWidgets.QCheckBox(self.windowFilterGroupBox)
        self.windowTrim.setChecked(True)
        self.windowTrim.setObjectName("windowTrim")
        self.gridLayout_6.addWidget(self.windowTrim, 0, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.windowFilterGroupBox)
        self.BandPassBox = QtWidgets.QGroupBox(self.LoadTab)
        self.BandPassBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BandPassBox.sizePolicy().hasHeightForWidth())
        self.BandPassBox.setSizePolicy(sizePolicy)
        self.BandPassBox.setMinimumSize(QtCore.QSize(505, 180))
        self.BandPassBox.setMaximumSize(QtCore.QSize(505, 16777215))
        self.BandPassBox.setCheckable(True)
        self.BandPassBox.setChecked(False)
        self.BandPassBox.setObjectName("BandPassBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.BandPassBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_19 = QtWidgets.QLabel(self.BandPassBox)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 1, 0, 1, 1)
        self.bandPassGO = QtWidgets.QPushButton(self.BandPassBox)
        self.bandPassGO.setStyleSheet("#bandPassGO {\n"
"    background: green;\n"
"}\n"
"\n"
"#bandPassGO:disabled{\n"
"    background: black;\n"
"}")
        self.bandPassGO.setObjectName("bandPassGO")
        self.gridLayout_7.addWidget(self.bandPassGO, 6, 3, 2, 2)
        self.lcdNumberFTauDead = QtWidgets.QLCDNumber(self.BandPassBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberFTauDead.sizePolicy().hasHeightForWidth())
        self.lcdNumberFTauDead.setSizePolicy(sizePolicy)
        self.lcdNumberFTauDead.setMinimumSize(QtCore.QSize(0, 0))
        self.lcdNumberFTauDead.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lcdNumberFTauDead.setStyleSheet("#lcdNumberFTauDead {\n"
"color: green;\n"
"background: black;\n"
"}\n"
"\n"
"#lcdNumberFTauDead:disabled {\n"
"color: grey;\n"
"background: dark grey;\n"
"}")
        self.lcdNumberFTauDead.setDigitCount(5)
        self.lcdNumberFTauDead.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumberFTauDead.setObjectName("lcdNumberFTauDead")
        self.gridLayout_7.addWidget(self.lcdNumberFTauDead, 2, 4, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.BandPassBox)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 1, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.BandPassBox)
        self.label_30.setObjectName("label_30")
        self.gridLayout_7.addWidget(self.label_30, 0, 0, 1, 1)
        self.filterDesignPushButton = QtWidgets.QPushButton(self.BandPassBox)
        self.filterDesignPushButton.setStyleSheet("")
        self.filterDesignPushButton.setObjectName("filterDesignPushButton")
        self.gridLayout_7.addWidget(self.filterDesignPushButton, 4, 3, 2, 2)
        self.stopBandSpinBox = QtWidgets.QDoubleSpinBox(self.BandPassBox)
        self.stopBandSpinBox.setMinimum(100.0)
        self.stopBandSpinBox.setMaximum(1600.0)
        self.stopBandSpinBox.setProperty("value", 280.0)
        self.stopBandSpinBox.setObjectName("stopBandSpinBox")
        self.gridLayout_7.addWidget(self.stopBandSpinBox, 2, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.BandPassBox)
        self.label_32.setObjectName("label_32")
        self.gridLayout_7.addWidget(self.label_32, 5, 0, 1, 1)
        self.passBandSpinBox = QtWidgets.QDoubleSpinBox(self.BandPassBox)
        self.passBandSpinBox.setMinimum(25.0)
        self.passBandSpinBox.setMaximum(600.0)
        self.passBandSpinBox.setSingleStep(5.0)
        self.passBandSpinBox.setProperty("value", 50.0)
        self.passBandSpinBox.setObjectName("passBandSpinBox")
        self.gridLayout_7.addWidget(self.passBandSpinBox, 1, 1, 1, 1)
        self.lcdNumberFilterOrder = QtWidgets.QLCDNumber(self.BandPassBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberFilterOrder.sizePolicy().hasHeightForWidth())
        self.lcdNumberFilterOrder.setSizePolicy(sizePolicy)
        self.lcdNumberFilterOrder.setStyleSheet("#lcdNumberFilterOrder {\n"
"color: green;\n"
"background: black;\n"
"}\n"
"\n"
"#lcdNumberFilterOrder:disabled {\n"
"color: grey;\n"
"background: dark grey;\n"
"}")
        self.lcdNumberFilterOrder.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumberFilterOrder.setObjectName("lcdNumberFilterOrder")
        self.gridLayout_7.addWidget(self.lcdNumberFilterOrder, 1, 4, 1, 1)
        self.gpassSpinBox = QtWidgets.QDoubleSpinBox(self.BandPassBox)
        self.gpassSpinBox.setSuffix("")
        self.gpassSpinBox.setDecimals(3)
        self.gpassSpinBox.setMaximum(1.0)
        self.gpassSpinBox.setSingleStep(0.01)
        self.gpassSpinBox.setProperty("value", 0.01)
        self.gpassSpinBox.setObjectName("gpassSpinBox")
        self.gridLayout_7.addWidget(self.gpassSpinBox, 3, 1, 2, 1)
        self.label_10 = QtWidgets.QLabel(self.BandPassBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 0, 2, 1, 1)
        self.plotBP = QtWidgets.QCheckBox(self.BandPassBox)
        self.plotBP.setEnabled(False)
        self.plotBP.setCheckable(True)
        self.plotBP.setChecked(True)
        self.plotBP.setObjectName("plotBP")
        self.gridLayout_7.addWidget(self.plotBP, 7, 0, 1, 1)
        self.CentralVSpinBox = QtWidgets.QDoubleSpinBox(self.BandPassBox)
        self.CentralVSpinBox.setDecimals(0)
        self.CentralVSpinBox.setMinimum(100.0)
        self.CentralVSpinBox.setMaximum(5001.0)
        self.CentralVSpinBox.setSingleStep(1.0)
        self.CentralVSpinBox.setProperty("value", 1000.0)
        self.CentralVSpinBox.setObjectName("CentralVSpinBox")
        self.gridLayout_7.addWidget(self.CentralVSpinBox, 0, 1, 1, 1)
        self.gstopSpinBox = QtWidgets.QDoubleSpinBox(self.BandPassBox)
        self.gstopSpinBox.setProperty("value", 5.0)
        self.gstopSpinBox.setObjectName("gstopSpinBox")
        self.gridLayout_7.addWidget(self.gstopSpinBox, 5, 1, 2, 1)
        self.label_20 = QtWidgets.QLabel(self.BandPassBox)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 2, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.BandPassBox)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 3, 0, 1, 1)
        self.fTypeComboBox = QtWidgets.QComboBox(self.BandPassBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fTypeComboBox.sizePolicy().hasHeightForWidth())
        self.fTypeComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.fTypeComboBox.setFont(font)
        self.fTypeComboBox.setMouseTracking(True)
        self.fTypeComboBox.setToolTip("")
        self.fTypeComboBox.setStatusTip("")
        self.fTypeComboBox.setWhatsThis("")
        self.fTypeComboBox.setObjectName("fTypeComboBox")
        self.fTypeComboBox.addItem("")
        self.fTypeComboBox.addItem("")
        self.fTypeComboBox.addItem("")
        self.gridLayout_7.addWidget(self.fTypeComboBox, 0, 3, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.BandPassBox)
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 2, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.BandPassBox)
        self.sumDataBox = QtWidgets.QGroupBox(self.LoadTab)
        self.sumDataBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sumDataBox.sizePolicy().hasHeightForWidth())
        self.sumDataBox.setSizePolicy(sizePolicy)
        self.sumDataBox.setMinimumSize(QtCore.QSize(505, 100))
        self.sumDataBox.setMaximumSize(QtCore.QSize(505, 200))
        self.sumDataBox.setCheckable(True)
        self.sumDataBox.setObjectName("sumDataBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.sumDataBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_5 = QtWidgets.QLabel(self.sumDataBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.sumDataBox)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_8.addWidget(self.comboBox, 0, 1, 1, 1)
        self.sumDataGO = QtWidgets.QPushButton(self.sumDataBox)
        self.sumDataGO.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sumDataGO.setStyleSheet("#sumDataGO {\n"
"    background: green;\n"
"}\n"
"\n"
"#sumDataGO:disabled{\n"
"    background: black;\n"
"}")
        self.sumDataGO.setObjectName("sumDataGO")
        self.gridLayout_8.addWidget(self.sumDataGO, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.sumDataBox)
        self.ProcTabs.addTab(self.LoadTab, "")
        self.QCTab = QtWidgets.QWidget()
        self.QCTab.setObjectName("QCTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.QCTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.qCalcGroupBox = QtWidgets.QGroupBox(self.QCTab)
        self.qCalcGroupBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qCalcGroupBox.sizePolicy().hasHeightForWidth())
        self.qCalcGroupBox.setSizePolicy(sizePolicy)
        self.qCalcGroupBox.setMinimumSize(QtCore.QSize(505, 100))
        self.qCalcGroupBox.setMaximumSize(QtCore.QSize(505, 150))
        self.qCalcGroupBox.setCheckable(True)
        self.qCalcGroupBox.setObjectName("qCalcGroupBox")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.qCalcGroupBox)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.calcQGO = QtWidgets.QPushButton(self.qCalcGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcQGO.sizePolicy().hasHeightForWidth())
        self.calcQGO.setSizePolicy(sizePolicy)
        self.calcQGO.setMinimumSize(QtCore.QSize(80, 20))
        self.calcQGO.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.calcQGO.setStyleSheet("#calcQGO {\n"
"    background: green;\n"
"}\n"
"\n"
"#calcQGO:disabled{\n"
"    background: black;\n"
"}")
        self.calcQGO.setObjectName("calcQGO")
        self.gridLayout_13.addWidget(self.calcQGO, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.qCalcGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 10))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_8.setObjectName("label_8")
        self.gridLayout_13.addWidget(self.label_8, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.qCalcGroupBox)
        self.FDSmartStackGroupBox = QtWidgets.QGroupBox(self.QCTab)
        self.FDSmartStackGroupBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FDSmartStackGroupBox.sizePolicy().hasHeightForWidth())
        self.FDSmartStackGroupBox.setSizePolicy(sizePolicy)
        self.FDSmartStackGroupBox.setMinimumSize(QtCore.QSize(505, 150))
        self.FDSmartStackGroupBox.setMaximumSize(QtCore.QSize(505, 16777215))
        self.FDSmartStackGroupBox.setCheckable(True)
        self.FDSmartStackGroupBox.setObjectName("FDSmartStackGroupBox")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.FDSmartStackGroupBox)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_37 = QtWidgets.QLabel(self.FDSmartStackGroupBox)
        self.label_37.setObjectName("label_37")
        self.gridLayout_14.addWidget(self.label_37, 0, 0, 1, 1)
        self.outlierTestCB = QtWidgets.QComboBox(self.FDSmartStackGroupBox)
        self.outlierTestCB.setObjectName("outlierTestCB")
        self.outlierTestCB.addItem("")
        self.outlierTestCB.addItem("")
        self.gridLayout_14.addWidget(self.outlierTestCB, 1, 0, 1, 1)
        self.FDSmartStackGO = QtWidgets.QPushButton(self.FDSmartStackGroupBox)
        self.FDSmartStackGO.setStyleSheet("#FDSmartStackGO {\n"
"    background: green;\n"
"}\n"
"\n"
"#FDSmartStackGO:disabled{\n"
"    background: black;\n"
"}")
        self.FDSmartStackGO.setObjectName("FDSmartStackGO")
        self.gridLayout_14.addWidget(self.FDSmartStackGO, 2, 1, 1, 1)
        self.MADCutoff = QtWidgets.QDoubleSpinBox(self.FDSmartStackGroupBox)
        self.MADCutoff.setDecimals(4)
        self.MADCutoff.setMaximum(10.0)
        self.MADCutoff.setProperty("value", 1.48)
        self.MADCutoff.setObjectName("MADCutoff")
        self.gridLayout_14.addWidget(self.MADCutoff, 1, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.FDSmartStackGroupBox)
        self.qdGroupBox = QtWidgets.QGroupBox(self.QCTab)
        self.qdGroupBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qdGroupBox.sizePolicy().hasHeightForWidth())
        self.qdGroupBox.setSizePolicy(sizePolicy)
        self.qdGroupBox.setMinimumSize(QtCore.QSize(505, 100))
        self.qdGroupBox.setMaximumSize(QtCore.QSize(505, 200))
        self.qdGroupBox.setCheckable(True)
        self.qdGroupBox.setObjectName("qdGroupBox")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.qdGroupBox)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.QDMethod = QtWidgets.QComboBox(self.qdGroupBox)
        self.QDMethod.setObjectName("QDMethod")
        self.QDMethod.addItem("")
        self.QDMethod.addItem("")
        self.QDMethod.addItem("")
        self.gridLayout_15.addWidget(self.QDMethod, 2, 2, 1, 1)
        self.plotQD = QtWidgets.QPushButton(self.qdGroupBox)
        self.plotQD.setEnabled(False)
        self.plotQD.setStyleSheet("#plotQD {\n"
"    background: green;\n"
"}\n"
"\n"
"#plotQD:disabled{\n"
"    background: black;\n"
"}")
        self.plotQD.setCheckable(False)
        self.plotQD.setObjectName("plotQD")
        self.gridLayout_15.addWidget(self.plotQD, 5, 3, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.qdGroupBox)
        self.label_42.setObjectName("label_42")
        self.gridLayout_15.addWidget(self.label_42, 2, 0, 1, 1)
        self.trimSpin = QtWidgets.QSpinBox(self.qdGroupBox)
        self.trimSpin.setMinimum(0)
        self.trimSpin.setProperty("value", 2)
        self.trimSpin.setObjectName("trimSpin")
        self.gridLayout_15.addWidget(self.trimSpin, 1, 2, 1, 1)
        self.qdGO = QtWidgets.QPushButton(self.qdGroupBox)
        self.qdGO.setStyleSheet("#qdGO {\n"
"    background: green;\n"
"}\n"
"\n"
"#qdGO:disabled{\n"
"    background: black;\n"
"}")
        self.qdGO.setObjectName("qdGO")
        self.gridLayout_15.addWidget(self.qdGO, 3, 3, 1, 1)
        self.QDType = QtWidgets.QComboBox(self.qdGroupBox)
        self.QDType.setObjectName("QDType")
        self.QDType.addItem("")
        self.QDType.addItem("")
        self.QDType.addItem("")
        self.gridLayout_15.addWidget(self.QDType, 5, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.qdGroupBox)
        self.label_38.setObjectName("label_38")
        self.gridLayout_15.addWidget(self.label_38, 1, 0, 1, 1)
        self.QDLoss = QtWidgets.QComboBox(self.qdGroupBox)
        self.QDLoss.setObjectName("QDLoss")
        self.QDLoss.addItem("")
        self.QDLoss.addItem("")
        self.QDLoss.addItem("")
        self.QDLoss.addItem("")
        self.gridLayout_15.addWidget(self.QDLoss, 2, 3, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.qdGroupBox)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_15.addWidget(self.line_10, 4, 2, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.qdGroupBox)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_15.addWidget(self.line_11, 4, 0, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.qdGroupBox)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_15.addWidget(self.line_12, 4, 3, 1, 1)
        self.verticalLayout_6.addWidget(self.qdGroupBox)
        self.gateBox = QtWidgets.QGroupBox(self.QCTab)
        self.gateBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gateBox.sizePolicy().hasHeightForWidth())
        self.gateBox.setSizePolicy(sizePolicy)
        self.gateBox.setMinimumSize(QtCore.QSize(505, 200))
        self.gateBox.setMaximumSize(QtCore.QSize(505, 200))
        self.gateBox.setCheckable(True)
        self.gateBox.setObjectName("gateBox")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.gateBox)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_53 = QtWidgets.QLabel(self.gateBox)
        self.label_53.setObjectName("label_53")
        self.gridLayout_16.addWidget(self.label_53, 0, 0, 1, 1)
        self.gateIntegrateGO = QtWidgets.QPushButton(self.gateBox)
        self.gateIntegrateGO.setStyleSheet("#gateIntegrateGO {\n"
"    background: green;\n"
"}\n"
"\n"
"#gateIntegrateGO:disabled{\n"
"    background: black;\n"
"}")
        self.gateIntegrateGO.setObjectName("gateIntegrateGO")
        self.gridLayout_16.addWidget(self.gateIntegrateGO, 0, 3, 1, 1)
        self.plotGI = QtWidgets.QPushButton(self.gateBox)
        self.plotGI.setEnabled(False)
        self.plotGI.setStyleSheet("#plotGI {\n"
"    background: green;\n"
"}\n"
"\n"
"#plotGI:disabled{\n"
"    background: black;\n"
"}")
        self.plotGI.setCheckable(False)
        self.plotGI.setObjectName("plotGI")
        self.gridLayout_16.addWidget(self.plotGI, 1, 3, 1, 1)
        self.GPDspinBox = QtWidgets.QSpinBox(self.gateBox)
        self.GPDspinBox.setMinimum(6)
        self.GPDspinBox.setMaximum(30)
        self.GPDspinBox.setProperty("value", 20)
        self.GPDspinBox.setObjectName("GPDspinBox")
        self.gridLayout_16.addWidget(self.GPDspinBox, 0, 1, 1, 1)
        self.QDType_2 = QtWidgets.QComboBox(self.gateBox)
        self.QDType_2.setObjectName("QDType_2")
        self.QDType_2.addItem("")
        self.QDType_2.addItem("")
        self.QDType_2.addItem("")
        self.gridLayout_16.addWidget(self.QDType_2, 1, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.gateBox)
        self.ProcTabs.addTab(self.QCTab, "")
        self.AppraiseTab = QtWidgets.QWidget()
        self.AppraiseTab.setObjectName("AppraiseTab")
        self.ProcTabs.addTab(self.AppraiseTab, "")
        self.LogTab = QtWidgets.QWidget()
        self.LogTab.setObjectName("LogTab")
        self.logTextBrowser = QtWidgets.QTextBrowser(self.LogTab)
        self.logTextBrowser.setGeometry(QtCore.QRect(10, 30, 921, 821))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logTextBrowser.sizePolicy().hasHeightForWidth())
        self.logTextBrowser.setSizePolicy(sizePolicy)
        self.logTextBrowser.setObjectName("logTextBrowser")
        self.label_74 = QtWidgets.QLabel(self.LogTab)
        self.label_74.setGeometry(QtCore.QRect(420, 10, 121, 20))
        self.label_74.setObjectName("label_74")
        self.ProcTabs.addTab(self.LogTab, "")
        self.verticalLayout_2.addWidget(self.ProcTabs)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 1, 1)
        self.groupBoxPlot = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPlot.sizePolicy().hasHeightForWidth())
        self.groupBoxPlot.setSizePolicy(sizePolicy)
        self.groupBoxPlot.setMinimumSize(QtCore.QSize(500, 0))
        self.groupBoxPlot.setTitle("")
        self.groupBoxPlot.setObjectName("groupBoxPlot")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxPlot)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mplwidget = MyDynamicMplCanvas(self.groupBoxPlot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwidget.sizePolicy().hasHeightForWidth())
        self.mplwidget.setSizePolicy(sizePolicy)
        self.mplwidget.setMinimumSize(QtCore.QSize(500, 300))
        self.mplwidget.setObjectName("mplwidget")
        self.verticalLayout.addWidget(self.mplwidget)
        self.mplwidget_navigator = MyDynamicMplCanvasNavigator(self.groupBoxPlot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwidget_navigator.sizePolicy().hasHeightForWidth())
        self.mplwidget_navigator.setSizePolicy(sizePolicy)
        self.mplwidget_navigator.setMinimumSize(QtCore.QSize(460, 38))
        self.mplwidget_navigator.setObjectName("mplwidget_navigator")
        self.verticalLayout.addWidget(self.mplwidget_navigator)
        self.headerFileBox = QtWidgets.QGroupBox(self.groupBoxPlot)
        self.headerFileBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headerFileBox.sizePolicy().hasHeightForWidth())
        self.headerFileBox.setSizePolicy(sizePolicy)
        self.headerFileBox.setMinimumSize(QtCore.QSize(460, 50))
        self.headerFileBox.setAcceptDrops(False)
        self.headerFileBox.setAutoFillBackground(False)
        self.headerFileBox.setFlat(False)
        self.headerFileBox.setCheckable(True)
        self.headerFileBox.setObjectName("headerFileBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.headerFileBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.headerFileTextBrowser = QtWidgets.QTextBrowser(self.headerFileBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headerFileTextBrowser.sizePolicy().hasHeightForWidth())
        self.headerFileTextBrowser.setSizePolicy(sizePolicy)
        self.headerFileTextBrowser.setMinimumSize(QtCore.QSize(0, 23))
        self.headerFileTextBrowser.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        self.headerFileTextBrowser.setFont(font)
        self.headerFileTextBrowser.setObjectName("headerFileTextBrowser")
        self.verticalLayout_4.addWidget(self.headerFileTextBrowser)
        self.headerBox2 = QtWidgets.QGroupBox(self.headerFileBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headerBox2.sizePolicy().hasHeightForWidth())
        self.headerBox2.setSizePolicy(sizePolicy)
        self.headerBox2.setMinimumSize(QtCore.QSize(540, 0))
        self.headerBox2.setTitle("")
        self.headerBox2.setObjectName("headerBox2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.headerBox2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_16 = QtWidgets.QLabel(self.headerBox2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.headerBox2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.lcdNumberTauPulse2 = QtWidgets.QLCDNumber(self.headerBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberTauPulse2.sizePolicy().hasHeightForWidth())
        self.lcdNumberTauPulse2.setSizePolicy(sizePolicy)
        self.lcdNumberTauPulse2.setStyleSheet("#lcdNumberTauPulse2 {\n"
"color: green;\n"
"background: black;\n"
"}\n"
"\n"
"#lcdNumberTauPulse2:disabled{\n"
"color: grey;\n"
"background: dark grey;\n"
"}")
        self.lcdNumberTauPulse2.setLineWidth(1)
        self.lcdNumberTauPulse2.setMidLineWidth(0)
        self.lcdNumberTauPulse2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumberTauPulse2.setObjectName("lcdNumberTauPulse2")
        self.gridLayout_3.addWidget(self.lcdNumberTauPulse2, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.headerBox2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.lcdNumberSampFreq = QtWidgets.QLCDNumber(self.headerBox2)
        self.lcdNumberSampFreq.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberSampFreq.sizePolicy().hasHeightForWidth())
        self.lcdNumberSampFreq.setSizePolicy(sizePolicy)
        self.lcdNumberSampFreq.setStyleSheet("#lcdNumberSampFreq {\n"
"color: green;\n"
"background: black;\n"
"}\n"
"\n"
"#lcdNumberSampFreq:disabled{\n"
"color: grey;\n"
"background: dark grey;\n"
"}")
        self.lcdNumberSampFreq.setLineWidth(1)
        self.lcdNumberSampFreq.setMidLineWidth(0)
        self.lcdNumberSampFreq.setDigitCount(5)
        self.lcdNumberSampFreq.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumberSampFreq.setObjectName("lcdNumberSampFreq")
        self.gridLayout_3.addWidget(self.lcdNumberSampFreq, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.headerBox2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.lcdNumberNQ = QtWidgets.QLCDNumber(self.headerBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberNQ.sizePolicy().hasHeightForWidth())
        self.lcdNumberNQ.setSizePolicy(sizePolicy)
        self.lcdNumberNQ.setStyleSheet("#lcdNumberNQ {\n"
"color: green;\n"
"background: black;\n"
"}\n"
"\n"
"#lcdNumberNQ:disabled{\n"
"color: grey;\n"
"background: dark grey;\n"
"}")
        self.lcdNumberNQ.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumberNQ.setObjectName("lcdNumberNQ")
        self.gridLayout_3.addWidget(self.lcdNumberNQ, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.headerBox2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 4, 0, 1, 1)
        self.lcdNumberTauPulse1 = QtWidgets.QLCDNumber(self.headerBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberTauPulse1.sizePolicy().hasHeightForWidth())
        self.lcdNumberTauPulse1.setSizePolicy(sizePolicy)
        self.lcdNumberTauPulse1.setStyleSheet("#lcdNumberTauPulse1 {\n"
"color: green;\n"
"background: black;\n"
"}\n"
"\n"
"#lcdNumberTauPulse1:disabled {\n"
"color: grey;\n"
"background: dark grey;\n"
"}")
        self.lcdNumberTauPulse1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumberTauPulse1.setLineWidth(1)
        self.lcdNumberTauPulse1.setMidLineWidth(0)
        self.lcdNumberTauPulse1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumberTauPulse1.setObjectName("lcdNumberTauPulse1")
        self.gridLayout_3.addWidget(self.lcdNumberTauPulse1, 2, 1, 1, 1)
        self.lcdNumberNuTx = QtWidgets.QLCDNumber(self.headerBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberNuTx.sizePolicy().hasHeightForWidth())
        self.lcdNumberNuTx.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lcdNumberNuTx.setFont(font)
        self.lcdNumberNuTx.setWhatsThis("")
        self.lcdNumberNuTx.setAutoFillBackground(False)
        self.lcdNumberNuTx.setStyleSheet("#lcdNumberNuTx {\n"
"color: green;\n"
"background: black;\n"
"}\n"
"\n"
"#lcdNumberNuTx:disabled {\n"
"color: grey;\n"
"background: dark grey;\n"
"}")
        self.lcdNumberNuTx.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumberNuTx.setLineWidth(1)
        self.lcdNumberNuTx.setMidLineWidth(0)
        self.lcdNumberNuTx.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumberNuTx.setProperty("value", 0.0)
        self.lcdNumberNuTx.setObjectName("lcdNumberNuTx")
        self.gridLayout_3.addWidget(self.lcdNumberNuTx, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.headerBox2)
        self.verticalLayout.addWidget(self.headerFileBox)
        self.gridLayout.addWidget(self.groupBoxPlot, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1142, 30))
        self.menubar.setObjectName("menubar")
        self.menuOpen_GMR_RAW_Header = QtWidgets.QMenu(self.menubar)
        self.menuOpen_GMR_RAW_Header.setObjectName("menuOpen_GMR_RAW_Header")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuProcessing = QtWidgets.QMenu(self.menubar)
        self.menuProcessing.setObjectName("menuProcessing")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_GMR = QtWidgets.QAction(MainWindow)
        self.actionOpen_GMR.setObjectName("actionOpen_GMR")
        self.actionOpen_Preprocessed_Dataset = QtWidgets.QAction(MainWindow)
        self.actionOpen_Preprocessed_Dataset.setObjectName("actionOpen_Preprocessed_Dataset")
        self.actionOpen_VC_Preprocessed_dataset = QtWidgets.QAction(MainWindow)
        self.actionOpen_VC_Preprocessed_dataset.setObjectName("actionOpen_VC_Preprocessed_dataset")
        self.actionSave_Preprocessed_Dataset = QtWidgets.QAction(MainWindow)
        self.actionSave_Preprocessed_Dataset.setObjectName("actionSave_Preprocessed_Dataset")
        self.actionExport_Preprocessed_Dataset = QtWidgets.QAction(MainWindow)
        self.actionExport_Preprocessed_Dataset.setObjectName("actionExport_Preprocessed_Dataset")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionAboutAkvo = QtWidgets.QAction(MainWindow)
        self.actionAboutAkvo.setObjectName("actionAboutAkvo")
        self.actionPreprocessing = QtWidgets.QAction(MainWindow)
        self.actionPreprocessing.setCheckable(True)
        self.actionPreprocessing.setChecked(True)
        self.actionPreprocessing.setObjectName("actionPreprocessing")
        self.actionModelling = QtWidgets.QAction(MainWindow)
        self.actionModelling.setCheckable(True)
        self.actionModelling.setObjectName("actionModelling")
        self.actionInversion = QtWidgets.QAction(MainWindow)
        self.actionInversion.setCheckable(True)
        self.actionInversion.setObjectName("actionInversion")
        self.menuOpen_GMR_RAW_Header.addAction(self.actionOpen_GMR)
        self.menuOpen_GMR_RAW_Header.addSeparator()
        self.menuOpen_GMR_RAW_Header.addAction(self.actionOpen_Preprocessed_Dataset)
        self.menuOpen_GMR_RAW_Header.addSeparator()
        self.menuOpen_GMR_RAW_Header.addAction(self.actionExport_Preprocessed_Dataset)
        self.menuOpen_GMR_RAW_Header.addSeparator()
        self.menuOpen_GMR_RAW_Header.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionAboutAkvo)
        self.menuProcessing.addAction(self.actionPreprocessing)
        self.menuProcessing.addAction(self.actionModelling)
        self.menuProcessing.addAction(self.actionInversion)
        self.menubar.addAction(self.menuOpen_GMR_RAW_Header.menuAction())
        self.menubar.addAction(self.menuProcessing.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.ProcTabs.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.inputRAWParametersBox.setTitle(_translate("MainWindow", "Input parameters"))
        self.label.setText(_translate("MainWindow", "Stacks"))
        self.stacksLineEdit.setPlaceholderText(_translate("MainWindow", "required"))
        self.label_24.setText(_translate("MainWindow", "Dead time [ms]"))
        self.DeadTimeSpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>This is the instrument dead time that is used. You may remove additonal or less dead time as an option. By default Akvo uses the recommended instrument dead times.</p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "Data Chs."))
        self.dataChanLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Set the data channels that you would like processed.</p><p>This must be a valid set of numpy array indices. Remember that Python uses non end-inclusive indexing. </p><p>So things like [1:3] will use channels 1 and 2</p><p>Any list of valid indices will be accepted, but they must be comma seperated. </p></body></html>"))
        self.dataChanLineEdit.setPlaceholderText(_translate("MainWindow", "required"))
        self.label_28.setText(_translate("MainWindow", "Reference Chs."))
        self.refChanLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Set the reference channels that you would like processed.</p><p>This must be a valid set of numpy array indices. Remember that Python uses non end-inclusive indexing. </p><p>So things like [1:3] will use channels 1 and 2</p><p>Any list of valid indices will be accepted, but they must be comma seperated. </p><p>Optionally no reference channels are allowed, just leave this field black so it says none</p></body></html>"))
        self.refChanLineEdit.setPlaceholderText(_translate("MainWindow", "none"))
        self.label_29.setText(_translate("MainWindow", "Process FID"))
        self.FIDProcComboBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>For T1 or CPMG pulses, which pulse(s) would you like to process. Note that for very short delay T1 pulses, the first pulse may be disabled. </p></body></html>"))
        self.plotImportCheckBox.setText(_translate("MainWindow", " Plot RAW"))
        self.loadDataPushButton.setText(_translate("MainWindow", "Load Data"))
        self.downSampleGroupBox.setTitle(_translate("MainWindow", "Downsample and truncate (anti-alias)"))
        self.truncateSpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Set the final length of your processed record. Note that the use of Adaptive filtering allows for the removal of additional late times. If you do not wish to truncate, leave as 0.</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Truncate [ms]"))
        self.label_12.setText(_translate("MainWindow", "Downsample factor"))
        self.downSampleGO.setText(_translate("MainWindow", "GO"))
        self.dsPlot.setText(_translate("MainWindow", "Plot"))
        self.windowFilterGroupBox.setTitle(_translate("MainWindow", "FD Window Filter (Central freq from IIR Band-Pass)"))
        self.label_55.setText(_translate("MainWindow", "dead time [ms]"))
        self.fdDesignPushButton.setText(_translate("MainWindow", "design"))
        self.windowFilterGO.setText(_translate("MainWindow", "GO"))
        self.label_48.setText(_translate("MainWindow", "Width [Hz]"))
        self.label_45.setText(_translate("MainWindow", "Type"))
        self.windowTypeComboBox.setItemText(0, _translate("MainWindow", "Hamming"))
        self.windowTypeComboBox.setItemText(1, _translate("MainWindow", "Hanning"))
        self.windowTypeComboBox.setItemText(2, _translate("MainWindow", "Flat top"))
        self.windowTypeComboBox.setItemText(3, _translate("MainWindow", "Rectangular"))
        self.windowTrim.setToolTip(_translate("MainWindow", "<html><head/><body><p>Sets whether or not the dead time will be trimmed from the beginning and end of the signal. When doing a cascade of filters, users may wish to hold off on edge effect removal. </p></body></html>"))
        self.windowTrim.setText(_translate("MainWindow", "Trim dead time "))
        self.BandPassBox.setTitle(_translate("MainWindow", "IIR Band-Pass Filter"))
        self.label_19.setText(_translate("MainWindow", "Pass Band [Hz]"))
        self.bandPassGO.setText(_translate("MainWindow", "GO"))
        self.label_18.setText(_translate("MainWindow", "Order"))
        self.label_30.setText(_translate("MainWindow", "Central ν Hz"))
        self.filterDesignPushButton.setText(_translate("MainWindow", "design"))
        self.label_32.setText(_translate("MainWindow", "gstop [dB]"))
        self.label_10.setText(_translate("MainWindow", "Type"))
        self.plotBP.setText(_translate("MainWindow", " Plot "))
        self.CentralVSpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>In case of off-resonant transmitter pulse, you can set the central frequency that will be used for all processing. This has the biggest impact on the band-pass filter, and the frequencies used in inversion. </p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "Stop Band [Hz]"))
        self.label_22.setText(_translate("MainWindow", "gpass [dB]"))
        self.fTypeComboBox.setAccessibleDescription(_translate("MainWindow", "Hello"))
        self.fTypeComboBox.setItemText(0, _translate("MainWindow", "Butterworth"))
        self.fTypeComboBox.setItemText(1, _translate("MainWindow", "Chebychev Type II"))
        self.fTypeComboBox.setItemText(2, _translate("MainWindow", "Elliptic"))
        self.label_21.setText(_translate("MainWindow", "dead time [ms]"))
        self.sumDataBox.setTitle(_translate("MainWindow", "Combine (sum) data channels"))
        self.label_5.setText(_translate("MainWindow", "Type"))
        self.comboBox.setItemText(0, _translate("MainWindow", "sum"))
        self.comboBox.setItemText(1, _translate("MainWindow", "difference"))
        self.sumDataGO.setToolTip(_translate("MainWindow", "<html><head/><body><p>For some types of multichannel data, the channels can be summed into composite channels. This method sums all channels down to a recursion level of 2.  For single loop datasets do not use this method.  </p></body></html>"))
        self.sumDataGO.setText(_translate("MainWindow", "GO"))
        self.ProcTabs.setTabText(self.ProcTabs.indexOf(self.LoadTab), _translate("MainWindow", "Load"))
        self.qCalcGroupBox.setTitle(_translate("MainWindow", "Pulse Moment Calculation "))
        self.calcQGO.setText(_translate("MainWindow", "GO"))
        self.label_8.setText(_translate("MainWindow", "Fourier-based calculation"))
        self.FDSmartStackGroupBox.setTitle(_translate("MainWindow", "TD SmartStac&k^TM"))
        self.label_37.setText(_translate("MainWindow", "Outlier test"))
        self.outlierTestCB.setItemText(0, _translate("MainWindow", "MAD"))
        self.outlierTestCB.setItemText(1, _translate("MainWindow", "none"))
        self.FDSmartStackGO.setText(_translate("MainWindow", "GO"))
        self.MADCutoff.setToolTip(_translate("MainWindow", "<html><head/><body><p>The threshold value used in the median absolute deviation outlier test. The default value of 1.4826 follows from an assumption of Gaussian noise, lower cutoff values are stricter and will throw out more samples.  </p></body></html>"))
        self.qdGroupBox.setTitle(_translate("MainWindow", "&Quadrature Detect"))
        self.QDMethod.setItemText(0, _translate("MainWindow", "Trust region reflective"))
        self.QDMethod.setItemText(1, _translate("MainWindow", "Dogbox"))
        self.QDMethod.setItemText(2, _translate("MainWindow", "Levenberg-Marquardt"))
        self.plotQD.setText(_translate("MainWindow", "PLOT"))
        self.label_42.setText(_translate("MainWindow", "Method/loss"))
        self.qdGO.setText(_translate("MainWindow", "GO"))
        self.QDType.setItemText(0, _translate("MainWindow", "Real/Imag"))
        self.QDType.setItemText(1, _translate("MainWindow", "Amp/Phase"))
        self.QDType.setItemText(2, _translate("MainWindow", "Phased"))
        self.label_38.setText(_translate("MainWindow", "Trim"))
        self.QDLoss.setItemText(0, _translate("MainWindow", "linear"))
        self.QDLoss.setItemText(1, _translate("MainWindow", "soft L1"))
        self.QDLoss.setItemText(2, _translate("MainWindow", "Cauchy"))
        self.QDLoss.setItemText(3, _translate("MainWindow", "Huber"))
        self.gateBox.setTitle(_translate("MainWindow", "Gate integrate"))
        self.label_53.setText(_translate("MainWindow", "Gates per decade "))
        self.gateIntegrateGO.setText(_translate("MainWindow", "GO"))
        self.plotGI.setText(_translate("MainWindow", "PLOT"))
        self.QDType_2.setItemText(0, _translate("MainWindow", "Real/Imag"))
        self.QDType_2.setItemText(1, _translate("MainWindow", "Amp/Phase"))
        self.QDType_2.setItemText(2, _translate("MainWindow", "Phased"))
        self.ProcTabs.setTabText(self.ProcTabs.indexOf(self.QCTab), _translate("MainWindow", "QC"))
        self.ProcTabs.setTabText(self.ProcTabs.indexOf(self.AppraiseTab), _translate("MainWindow", "Appraisal"))
        self.logTextBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">All processing steps are recorded here for your records</span></p></body></html>"))
        self.label_74.setText(_translate("MainWindow", "Processing log"))
        self.ProcTabs.setTabText(self.ProcTabs.indexOf(self.LogTab), _translate("MainWindow", "Log"))
        self.headerFileBox.setTitle(_translate("MainWindow", "Expand grid information "))
        self.headerFileTextBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:8pt; font-weight:400; font-style:italic;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'DejaVu Serif\'; font-size:9pt;\">Load supported RAW Dataset header from file menu</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "NZ"))
        self.label_9.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of pulse moments (q)</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "NX"))
        self.label_7.setText(_translate("MainWindow", "NY "))
        self.label_6.setText(_translate("MainWindow", "ν Tx  [Hz]"))
        self.label_15.setText(_translate("MainWindow", "N active "))
        self.menuOpen_GMR_RAW_Header.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuProcessing.setTitle(_translate("MainWindow", "Workflows"))
        self.actionOpen_GMR.setText(_translate("MainWindow", "&Open GRDECL "))
        self.actionOpen_Preprocessed_Dataset.setText(_translate("MainWindow", "Open TOUGH MESH"))
        self.actionOpen_VC_Preprocessed_dataset.setText(_translate("MainWindow", "Open VC Preprocessed dataset"))
        self.actionSave_Preprocessed_Dataset.setText(_translate("MainWindow", "Save processing "))
        self.actionExport_Preprocessed_Dataset.setText(_translate("MainWindow", "Export to VTK "))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionAboutAkvo.setText(_translate("MainWindow", "About"))
        self.actionPreprocessing.setText(_translate("MainWindow", "Preprocessing"))
        self.actionModelling.setText(_translate("MainWindow", "Modelling"))
        self.actionInversion.setText(_translate("MainWindow", "Inversion"))
from akvo.gui.mydynamicmplcanvas import MyDynamicMplCanvas
from akvo.gui.mydynamicmplcanvasnavigator import MyDynamicMplCanvasNavigator
